name: jsii publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
      env:
        HUSKY_SKIP_INSTALL: 1

    - name: Build source
      uses: udondan/jsii-publish@v0.8.3
      with:
        VERSION: ${{ steps.get_version.outputs.VERSION }}
        BUILD_SOURCE: true

    - name: Build packages
      uses: udondan/jsii-publish@v0.8.3
      with:
        BUILD_PACKAGES: true

    - name: Publish to npm
      uses: udondan/jsii-publish@v0.8.3
      with:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish to PyPI
      uses: udondan/jsii-publish@v0.8.3
      with:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

    - name: Publish to NuGet
      uses: udondan/jsii-publish@v0.8.3
      with:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}

    - name: Publish to Maven GitHub
      uses: udondan/jsii-publish@v0.8.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}